development:
  adapter: postgresql
  database: t2
  host: localhost

test:
  adapter: postgresql
  database: t2_test
  host: localhost

production:
  adapter: postgresql
  database: t2
  host: localhost